version: '3.8'

services:
  bff:
    build:
      context: ../src/BFF
      dockerfile: Dockerfile
    ports:
      - "5001:80"  # external:internal
    environment:
     - ASPNETCORE_URLS=http://+:80

  inventory:
    build:
      context: ../src/Inventory Service API
      dockerfile: Dockerfile
    ports:
      - "5002:80"  # external:internal
    environment:
     - ASPNETCORE_URLS=http://+:80

  payment:
    build:
      context: ../src/Payment Service API
      dockerfile: Dockerfile
    ports:
      - "5003:80"  # external:internal
    environment:
     - ASPNETCORE_URLS=http://+:80

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bff
      - inventory
      - payment
